development:
  adapter: jdbc
  driver: org.apache.derby.jdbc.ClientDriver
  url: jdbc:derby:tipptop_development;create=true
  username: app
  password: app

production:
  adapter: jdbc
  driver: org.apache.derby.jdbc.ClientDriver
  url: jdbc:derby:tipptop_development;create=false
  username: app
  password: app
