# Test ohne echtes Versenden von Mails
development:
  :delivery_method: test
  :address: localhost
  :port: 25
  :authentication: plain
  :user_name: motu@tipptop.net
  :password: wdlid

#  ACHTUNG: Hier werden echte Emails versendet. Passwort sollte nicht herausgegeben werden 
production:
 :delivery_method: :smtp
 :address: smtp.tipptop.net
 :port: 25
 :authentication: plain
 :user_name: motu@tipptop.net
 :password: topsecret
